### ISSUE TITLE
📌 Guide To making an issue

### ISSUE THREAD

**Issue by Autofirejm** [lopste/forumoji#12]
## Welcome to the guide on how to make an issue!

- Is there a bug with the webpage? report it [here](https://github.com/Autofirejm/autofirejm.github.io/issues)
- Is the Post on the topic wrong? - Acceptable
- Have a question? ask it [here!](https://github.com/lopste/emodjiango/discussions/q-a)
- Any emoji's removed or not on the repository? - Acceptable
- Is there a bug with the Item generator? - Acceptable

### Keep in mind that this guide is **Very** incomplete! any suggestions to add to the guide are Welcome!

**Comment by kccuber-scratch** [comment]
Lol it linked to autofirejm/autofirejm.github.io/issues so i fixed it

**Comment by Autofirejm** [comment]
> Lol it linked to autofirejm/autofirejm.github.io/issues so i fixed it

lol
