### ISSUE TITLE
You can get a eu.org domain for this

### ISSUE THREAD

**Issue by PoIygon** [lopste/forumoji#16]
You should get an eu.org domain for this so it looks professional

**Comment by lopste** [comment]
Does it really need it? I feel like .github.io isn't too bad. If I really want, I could just actually register a domain for it.

**Comment by kccuber-scratch** [comment]
For such a simple purpose I don't think it needs it's own domain.

**Comment by ILOVETOMAKESTUFF** [comment]
eu.org is blocked. Just because many other webs use it, doesn't mean this one does.

**Comment by Steve0Greatness** [comment]
I don't think anybody really cares if the domain looks official or not.

**Comment by veloce-vasta** [comment]
It looks good with .vercte.net
