### ISSUE TITLE
Emoji Request: Test issue please ignore

### ISSUE THREAD

**Issue by kccuber-scratch** [lopste/forumoji#20]
Scratch Username: test
Official Emoji Name: test
Unicode codepoint: test
Link to emoji (On cubeupload or assets): test

**Comment by kccuber-scratch** [comment]
Sorry, was just testing github rest api and grep and needed this issue

**Comment by kccuber-scratch** [comment]
please keep this issue open, i will close it when I finish testing

**Comment by CocoTheMii** [comment]
I'm assuming this test is done now?
