### ISSUE TITLE
Emoji Request: face with crossed-out eyes

### ISSUE THREAD

**Issue by ghost** [lopste/forumoji#29]
Scratch Username: ISTILLMAKESTUFF
Official Emoji Name: face with crossed-out eyes
Unicode codepoint: U+1F635
Link to emoji (On cubeupload or assets):
![New Piskel-1 png](https://user-images.githubusercontent.com/97681427/171675928-87064490-341a-43db-8272-357a709206a8.png)

**Comment by Steve0Greatness** [comment]
I think it needs to be hosted on Scratch Assets or CubeUpload, not GitHub.  
https://assets.scratch.mit.edu/get_image/.%2E/83b5d0f7f203d3f5125630f9c73d2913.png

**Comment by ILOVETOMAKESTUFF** [comment]
Yeah, but I cant access those :( Thanks for the link!
