### ISSUE TITLE
Emoji Request: Black Bird

### ISSUE THREAD

**Issue by mybearworld** [lopste/forumoji#39]
Official Emoji Name: BLACK BIRD
Unicode codepoint: U+1F426 U+200D U+2B1B
Link to emoji (On cubeupload or assets): https://assets.scratch.mit.edu/6f1bb911aad77a088b6fb8cb09b25358.png ![bird](https://user-images.githubusercontent.com/130385691/231565887-de14666b-f54a-42b4-ab05-ee1a20c2b63a.png)
An adaptation of notwait's BIRD.

**Comment by notwait** [comment]
I had made that one back in February, but whoever put the normal bird forgot to put the black bird https://u.cubeupload.com/notwait/blackbird.png 
https://scratch.mit.edu/discuss/post/6968863/

**Comment by CocoTheMii** [comment]
I've added @notwait's version; its colour scheme is more in line with the rest of the emojis.

> I had made that one back in February, but whoever put the normal bird forgot to put the black bird

That would be @lopste. The black bird emoji is new to Emoji 15.0, which I had just added support for, so he may have assumed it wasn't supported.
