### ISSUE TITLE
Change the seperator between authors from \n to ,

### ISSUE THREAD

**Issue by Steve0Greatness** [lopste/forumoji#42]
Commas just make more sense. And since authors are credited using their Scratch username, it won't impact the parsability. All this will end up doing is make it easier to read when editing `forumoji.json`, since some syntax-highlighters(such as GitHub's) do not change the color of `\n`s to contrast them from the rest of the text, at least not in JSON strings.

**Comment by mybearworld** [comment]
It could just also be an array, which the website then displayed correctly.

**Comment by Steve0Greatness** [comment]
That would be better, actually. I think(don't quote me on this, but) all that would need to be changed is `list.js` line `132`, in-which the usage of `.replace('\n', '<br>')` would only need to be changed to `.join('<br>')`.
