### ISSUE TITLE
Emojis displaying as black-and-white symbols

### ISSUE THREAD

**Issue by CocoTheMii** [lopste/forumoji#67]
Some emojis have a black-and-white symbol variant, in addition to their coloured emoji variant. For the emoji variant of these symbols, the codepoint `U+FE0F` is appended to indicate that the symbol is an emoji.

Some of the emojis on the website incorrectly display their black-and-white symbol variants instead of their colourful emoji variants; for example, the red heart emoji:

![image](https://github.com/lopste/forumoji/assets/44563370/ed392ce0-7b22-4ab6-8e2a-c8ca510ea7a1)

As you can see, the emoji is lacking the `U+FE0F` codepoint that tells it to display in colour. This problem seems to stem from the fact that the [charts on the Unicode website](https://www.unicode.org/emoji/charts/emoji-list.html) do not include the `U+FE0F` codepoint; however, it is seen [in data files](https://unicode.org/Public/emoji/latest/emoji-test.txt):

![image](https://github.com/lopste/forumoji/assets/44563370/eade2fdc-470d-42f9-a537-af55ada015a0)

To fix this, `unicode-emoji.json` and `forumoji.json` should be updated to fix the codepoints. Unfortunately, due to the number of emojis that have been added so far, this is quite a large undertaking if one were to do it manually.

I have been looking into automating the creation of a new `unicode-emoji.json` file that would fix this problem. I'm currently working on a Python script to do this, although it is proving to be somewhat troublesome.

**Comment by lopste** [comment]
Fixed in the newest version of the website.
