### ISSUE TITLE
Assets links don't work on the forums anymore

### ISSUE THREAD

**Issue by Chiroyce1** [lopste/forumoji#68]
https://github.com/ScratchAddons/ScratchAddons/issues/6913

So after the 4-5 days of forum downtime, there seem to be a lot of changes to the post filter, which in turn blocks posting image links containing `assets.scratch.mit.edu/get_image/` - so when someone tries to post a forumoji with the Scratch host, Scratch shows a message saying
> Sorry, this post appears to include unsuitable language and will not be posted.

**Comment by lopste** [comment]
Image hosting has been moved to Cubeupload, so this issue shouldn't be of relevance anymore.
