### ISSUE TITLE
CubeUpload Migration

### ISSUE THREAD

**Issue by Steve0Greatness** [lopste/forumoji#69]
I was able to claim `forumoji` on CubeUpload, so I've uploaded all emojis to it, they can be found at `https://u.cubeupload.com/forumoji/<emoji-id*>.png`. EG: https://u.cubeupload.com/forumoji/1f1e91f1ea.png.

Please notify me when emojis are changed so I can replace them. Also let me know if a file uploaded incorrectly and has an incorrect id.

To maintainers: I'd be happy to send the password via DMs(outside GitHub, it doesn't provide DMs).

\* This should be the ones seen in `emoji.json`, but without hyphens(`-`) since CubeUpload does not allow them in filenames. EG: `1f1e9-1f1ea` would become `1f1e91f1ea`.

**Comment by lopste** [comment]
Man... I don't know if you got the news or not, but I already did it with the shorter username fmji.
Thank you for your troubles, but they were kinda in vain—may be useful for those who try the full name, though.
