### ISSUE TITLE
Color pallet has too little contrast [A11Y]

### ISSUE THREAD

**Issue by Steve0Greatness** [lopste/forumoji#74]
This was previously closed as completed, it wasn't.

Accent color to text color: [test results](https://color.a11y.com/ContrastPair/?bgcolor=ff8c00&fgcolor=ffffff), [(other way around)](https://color.a11y.com/ContrastPair/?bgcolor=ffffff&fgcolor=ff8c00)

Orange and white do not work well as accessible colors when together. A better color match for all use case of orange and black.

However, I don't think this would work well for the category toolbar nor as the background color of the emojis once selected; I'd suggest using black in-place of orange in these cases.

Here's what the page would look like if such changes were to be implemented:

![](https://github.com/lopste/forumoji/assets/75220768/69951ae6-d75b-4393-acf3-c6cbc7e6773a)

**Comment by lopste** [comment]
duplicate due to my haphazard closing
